[package]
name = "dpcore"
version = "2.2.0"
publish = false
edition = "2018"
license = "GPLv3"

[dependencies]
base64 = "0.11.0"
serde_json = "1.0.44"
tracing = "0.1.22"
num_enum = "0.5.4"
bitvec = "0.22.3"
inflate = "0.4.5"
deflate = "0.8.4"
lazy_static = "1.4.0"

[dev-dependencies]
itertools = "0.8.2"
image = "0.22.3"
criterion = "0.3"

[[bench]]
name = "rasterops"
harness = false

[[bench]]
name = "brushdabs"
harness = false
