[package]
name = "dpimpex"
version = "0.1.0"
publish = false
edition = "2018"
license = "GPLv3"

[dependencies]
dpcore = { path = "../dpcore" }
xml-rs = "0.8.4"
tracing = "0.1.22"

[dependencies.image]
version = "0.23.14"
default-features = false
features = ["png", "jpeg", "tiff", "gif"]

[dependencies.zip]
version = "0.5.13"
default-features = false
features = ["deflate"]
