[package]
name = "dpimpex"
version = "0.1.0"
publish = false
edition = "2018"
license = "GPLv3"

[dependencies]
dpcore = { path = "../dpcore" }

[dependencies.image]
version = "0.23.14"
default-features = false
features = ["png", "jpeg", "tiff", "gif"]

