[package]
name = "rustpile"
version = "0.1.0"
publish = false
edition = "2018"
license = "GPLv3"

[lib]
crate-type = ["staticlib"]

[dependencies]
dpcore = { path = "../dpcore" }
dpimpex = { path = "../dpimpex" }
tracing-subscriber = "0.1.6"
tracing = "0.1.5"

