name: Build

on: [push]

env:
  DRAWDANCE_REPO: "https://github.com/cow54787/Drawdance.git"
  DRAWDANCE_BRANCH: "windows-build"
  VCPKG_DEFAULT_BINARY_CACHE: "C:/vcpkg-cache"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - run: mkdir $Env:VCPKG_DEFAULT_BINARY_CACHE

      - name: Cache vcpkg deps
        uses: actions/cache@v3
        with:
          path: C:/vcpkg-cache
          key: ${{ runner.os }}-build-vcpkg-deps
          restore-keys: |
            ${{ runner.os }}-build-build-vcpkg-deps-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "Download Drawdance"
        run: |
          pushd C:/ 
          git clone -b $Env:DRAWDANCE_BRANCH $Env:DRAWDANCE_REPO drawdance
          popd
      
      - name: "Build"
        run : |
          pushd pkg/win-msvc/
          ./build-release.ps1 -drawdanceDir C:/drawdance
          popd

      - name: "Package"
        run : |
          pushd pkg/win-msvc/
          ./package.ps1
          popd

      - uses: actions/upload-artifact@v3
        with:
          name: drawpile-win-msvc
          path: pkg/win-msvc/drawpile-win-msvc.zip
